apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: awsefscsiprovisioner
  labels:
    kubeaddons.mesosphere.io/name: awsebscsiprovisioner
    kubeaddons.mesosphere.io/provides: storageclass
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.8.0-1"
    appversion.kubeaddons.mesosphere.io/awsebscsiprovisioner: "0.8.0"
    values.chart.helm.kubeaddons.mesosphere.io/awsebscsiprovisioner: "https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/e7cebc79b59915e9aa8c44b1ed58c8af5e54c826/charts/aws-efs-csi-driver/values.yaml"
spec:
  namespace: kube-system
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
  chartReference:
    version: 0.5.0
    chart: awsefscsiprovisioner
    #repo: https://mesosphere.github.io/charts/stable
    repo: https://kubernetes-sigs.github.io/aws-efs-csi-driver/charts
    values: |
      ---
      resizer:
        enabled: true
      snapshotter:
        enabled: true
      provisioner:
        enableVolumeScheduling: true
      storageclass:
        name: efs-sc
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        